# Generated by Django 5.0.7 on 2024-09-19 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип комиссии')),
            ],
            options={
                'verbose_name': 'Тип комиссии',
                'verbose_name_plural': 'Типы комиссий',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_num', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ФИО')),
                ('image', models.ImageField(default='/images/emp_def.webp', null=True, upload_to='images/')),
                ('level', models.IntegerField(blank=True, verbose_name='Разряд')),
                ('department', models.TextField(blank=True, choices=[('Отдел управления проектами', 'Отдел управления проектами'), ('Отдел технического обслуживания', 'Отдел технического обслуживания'), ('Отдел исследования и разработки', 'Отдел исследования и разработки')], max_length=255, null=True, verbose_name='Должность')),
                ('position', models.TextField(blank=True, choices=[('Начальник отдела', 'Начальник отдела'), ('Главный специалист', 'Главный специалист'), ('Ведущий специалист', 'Ведущий специалист')], max_length=255, null=True, verbose_name='Должность')),
                ('enter', models.CharField(max_length=255, verbose_name='Период работы(с)')),
                ('pos_duration', models.IntegerField(verbose_name='Длительность на должности')),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(null=True, upload_to='files/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название станции')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(default='Описание', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Роль пользователя')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('leader', models.CharField(blank=True, max_length=255, null=True, verbose_name='Председатель комиссии')),
                ('image', models.ImageField(blank=True, default='/media/images/emp_def.webp', null=True, upload_to='images/', verbose_name='Протокол комиссии')),
                ('lvl', models.CharField(max_length=255, verbose_name='Уровень комиссии')),
                ('group', models.CharField(max_length=120, verbose_name='Номер группы')),
                ('commission_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.commissiontype', verbose_name='Тип комиссии')),
                ('members', models.ManyToManyField(blank=True, related_name='member_commissions', to='TES.employee', verbose_name='Члены комиссии')),
                ('files', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.files', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Комиссия',
                'verbose_name_plural': 'Комиссии',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип экзамена')),
                ('types', models.CharField(blank=True, choices=[('secure', 'Техника безопасности'), ('fire', 'Пожарная безопасность'), ('med', 'Медицинский контроль')], max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.commission', verbose_name='Комиссия')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.plants', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.plants', verbose_name='Станция'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('status', models.CharField(blank=True, choices=[('pass', 'Прошел'), ('fail', 'Не прошел'), ('process', 'В процессе')], max_length=255, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='экзамен', to='TES.exam', verbose_name='Тип экзамена')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.employee', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('password', models.CharField(default='TES123456789', max_length=255, verbose_name='Пароль')),
                ('role', models.ManyToManyField(related_name='users', to='TES.userrole', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
