# Generated by Django 5.0.7 on 2024-09-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Разряд'),
        ),
    ]
