# Generated by Django 5.0.7 on 2024-08-21 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип комиссии')),
            ],
            options={
                'verbose_name': 'Тип комиссии',
                'verbose_name_plural': 'Типы комиссий',
            },
        ),
        migrations.RemoveField(
            model_name='employer',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'verbose_name': 'Комиссия', 'verbose_name_plural': 'Комиссии'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RemoveField(
            model_name='employer',
            name='score',
        ),
        migrations.AddField(
            model_name='commission',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='commission',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.files', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='commission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.commission', verbose_name='Комиссия'),
        ),
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='employer',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.exam', verbose_name='Тип экзамена'),
        ),
        migrations.AddField(
            model_name='employer',
            name='image',
            field=models.ImageField(default='/media/images/emp_def.webp', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.plants', verbose_name='Станция'),
        ),
        migrations.AddField(
            model_name='exam',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.plants', verbose_name='Станция'),
        ),
        migrations.AddField(
            model_name='exam',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='plants',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='TES123456789', max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='lvl',
            field=models.CharField(max_length=255, verbose_name='Уровень комиссии'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='user_name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.FileField(null=True, upload_to='files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(related_name='users', to='TES.userrole', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='commission',
            name='commission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.commissiontype', verbose_name='Тип комиссии'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('status', models.CharField(blank=True, choices=[('pass', 'Прошел'), ('fail', 'Не прошел'), ('process', 'В процессе')], max_length=255, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='экзамен', to='TES.exam', verbose_name='Тип экзамена')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.employer', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
