# Generated by Django 5.0.7 on 2024-08-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0002_commissiontype_remove_employer_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='image',
            field=models.ImageField(blank=True, default='/media/images/emp_def.webp', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='image',
            field=models.ImageField(default='/images/emp_def.webp', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='position',
            field=models.TextField(blank=True, choices=[('pass', 'Прошел'), ('fail', 'Не прошел'), ('process', 'В процессе')], max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
