# Generated by Django 5.0.7 on 2024-09-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0002_alter_employee_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='enter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Период работы(с)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pos_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность на должности'),
        ),
    ]
