# Generated by Django 5.0.7 on 2024-07-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0002_files_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.plants'),
        ),
    ]
