# Generated by Django 5.0.7 on 2024-07-24 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0003_employer_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип каммиссии')),
            ],
            options={
                'verbose_name': 'Тип камиссии',
                'verbose_name_plural': 'Типы камиссий',
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='commission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.commissiontype'),
        ),
    ]
