# Generated by Django 5.0.7 on 2024-09-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0003_alter_employee_enter_alter_employee_pos_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_num',
            field=models.CharField(blank=True, max_length=10, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='/images/emp_def.webp', null=True, upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место рождения'),
        ),
    ]
