# Generated by Django 5.0.7 on 2024-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0003_alter_commission_image_alter_employer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='department',
            field=models.TextField(blank=True, choices=[('Отдел управления проектами', 'Отдел управления проектами'), ('Отдел технического обслуживания', 'Отдел технического обслуживания'), ('Отдел исследования и разработки', 'Отдел исследования и разработки')], max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='position',
            field=models.TextField(blank=True, choices=[('Начальник отдела', 'Начальник отдела'), ('Главный специалист', 'Главный специалист'), ('Ведущий специалист', 'Ведущий специалист')], max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
