# Generated by Django 5.0.7 on 2024-08-21 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0004_employer_department_alter_employer_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='commission',
            field=models.ForeignKey(blank=True, default='Не состоит в комиссии', null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.commission', verbose_name='Комиссия'),
        ),
    ]
