# Generated by Django 5.0.7 on 2024-08-21 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0005_alter_employer_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='user_name',
        ),
        migrations.AddField(
            model_name='commission',
            name='leader',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Председатель комиссии'),
        ),
        migrations.AddField(
            model_name='commission',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.commission', verbose_name='Комиссия'),
        ),
    ]
