# Generated by Django 5.0.7 on 2024-07-24 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0005_score_alter_employer_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.exam'),
        ),
        migrations.AddField(
            model_name='score',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.employer'),
        ),
    ]
