# Generated by Django 5.0.7 on 2024-07-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0006_remove_employer_score_score_exam_score_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='category',
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
