# Generated by Django 5.0.7 on 2024-09-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0006_remove_commission_user_name_commission_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Тип экзамена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(blank=True, choices=[('tb', 'Экзамен по ТБ'), ('med', 'Экзамен по Медицине'), ('fire', 'Экзамен по Пожарной безопасности')], max_length=255, null=True),
        ),
    ]
