# Generated by Django 5.0.7 on 2024-07-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0008_alter_commission_commission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='plants',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
