# Generated by Django 5.0.7 on 2024-07-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0010_exam_plant_alter_commission_lvl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_title', models.CharField(max_length=200)),
                ('event_theme', models.CharField(choices=[('blue', 'Blue Theme'), ('red', 'Red Theme'), ('yellow', 'Yellow Theme'), ('green', 'Green Theme'), ('purple', 'Purple Theme')], max_length=20)),
            ],
        ),
    ]
