# Generated by Django 5.0.7 on 2024-07-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0011_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
