# Generated by Django 5.0.7 on 2024-08-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0012_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='employer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
