# Generated by Django 5.0.7 on 2024-08-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0013_commission_description_employer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
