# Generated by Django 5.0.7 on 2024-08-02 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0014_commission_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.commission', verbose_name='Камиссия'),
        ),
    ]
