# Generated by Django 5.0.7 on 2024-08-02 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0016_alter_employer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.exam', verbose_name='Тип экзамена'),
        ),
    ]
