# Generated by Django 5.0.7 on 2024-08-05 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0017_employer_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='exam',
        ),
    ]
