# Generated by Django 5.0.7 on 2024-08-05 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0018_remove_employer_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.exam'),
        ),
        migrations.AlterField(
            model_name='score',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ФИО', to='TES.employer'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Оценка', to='TES.employer'),
        ),
    ]
