# Generated by Django 5.0.7 on 2024-08-05 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0021_remove_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='exam',
        ),
    ]
