# Generated by Django 5.0.7 on 2024-08-05 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0024_alter_score_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='commission',
        ),
        migrations.AddField(
            model_name='commission',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.files', verbose_name='Файл'),
        ),
    ]
