# Generated by Django 5.0.7 on 2024-08-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0029_remove_user_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123, max_length=255, verbose_name='Пароль'),
        ),
    ]
