# Generated by Django 5.0.7 on 2024-08-14 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0032_status_score_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TES.category', verbose_name='Стат'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
