# Generated by Django 5.0.7 on 2024-08-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0033_alter_score_status_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='status',
            field=models.CharField(blank=True, choices=[('pass', 'Прошел'), ('fail', 'Не прошел'), ('process', 'В процессе')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
