# Generated by Django 5.0.7 on 2024-08-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0036_alter_employer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='image',
            field=models.ImageField(default='/media/images/emp_def.webp', null=True, upload_to='images/'),
        ),
    ]
