# Generated by Django 5.0.7 on 2024-08-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0038_alter_commission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='leader',
            field=models.CharField(default='Лидер', max_length=255, verbose_name='ФИО'),
        ),
    ]
