# Generated by Django 5.0.7 on 2024-08-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0039_alter_commission_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='leader',
            field=models.CharField(default='Лидер', max_length=255, null=True, verbose_name='ФИО'),
        ),
    ]
