# Generated by Django 5.0.7 on 2024-08-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0040_alter_commission_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='leader',
        ),
    ]
